[package]
name = "rust_game_networking"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.63.0"
cc = "1.0.79"

[dev-dependencies]
ctrlc = "3.2.5"
